### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by salvatoreNRIM** [itsasimiqbal/StARQ#1]
Hello, have been trying to install StARQ following the instruction on Github but when I run the command
`pip install -r requirements.txt`
I get `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`
And in fact there is no requirements.txt file in the StARQ folder. Do you have any idea?

**Comment by itsasimiqbal** [comment]
Hello! Please run the following Google Colab for testing: https://colab.research.google.com/github/itsasimiqbal/StARQ/blob/main/StARQ_2_0_2024.ipynb
